version: '3'
services:
  setup:
    build:
      context: ../docker
      dockerfile: strongbox/strongbox-setup.Dockerfile
    env_file: ../.env
    environment:
      NEW: $NEW
    volumes:
      - sync:/home/provable/sync
      - ../enclave-proxy:/home/provable/proxy
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true

  syncer_native:
    image: provable/ptokens-btc-syncer:1.15.3-strongbox
    env_file: ../.env
    environment:
      ROLE: native
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - sync:/home/provable/sync
      - syncer_native_nm:/home/provable/syncer/node_modules
      - ../enclave-proxy:/home/provable/proxy
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped

  syncer_host:
    image: provable/ptokens-eos-syncer:2.17.0-strongbox
    env_file: ../.env
    environment:
      ROLE: host
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - sync:/home/provable/sync
      - syncer_host_nm:/home/provable/syncer/node_modules
      - ../enclave-proxy:/home/provable/proxy
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped

  api:
    image: provable/ptokens-api-server:1.12.12-strongbox
    env_file: ../.env
    volumes:
      - sync:/home/provable/sync
      - api_server_nm:/home/provable/api-server/node_modules
      - ../enclave-proxy:/home/provable/proxy
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped
    
  broadcaster_native:
    image: provable/ptokens-btc-tx-broadcaster:1.1.2
    env_file: ../.env
    environment:
      ROLE: native
    environment:
      ENDPOINT_NATIVE_NODE: https://btc-node-2.ptokens.io/
      API_ENDPOINT_TYPE: esplora
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - broadcaster_native_nm:/home/provable/broadcaster/node_modules
      - sync:/home/provable/sync
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped

  broadcaster_host:
    image: provable/ptokens-eos-tx-broadcaster:1.6.0
    env_file: ../.env
    environment:
      ROLE: host
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - broadcaster_host_nm:/home/provable/broadcaster/node_modules
      - sync:/home/provable/sync
      - /dev/bus/usb/:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped

volumes:
  sync:
  pnpm-store:
  api_server_nm:
  syncer_host_nm:
  syncer_native_nm:
  broadcaster_host_nm:
  broadcaster_native_nm:
  smart_contract_generator_nm:
