version: '3'
services:
  setup:
    build:
      context: ../../docker
      dockerfile: strongbox/strongbox-setup.Dockerfile
    env_file: ../../.env
    environment:
      NEW: $NEW
    volumes:
      - sync:/home/provable/sync
      - /dev/bus/usb/:/dev/bus/usb
      - ../../enclave-proxy:/home/provable/proxy
    network_mode: host
    privileged: true

volumes:
  sync:
  pnpm-store:
  api_server_nm:
  syncer_host_nm:
  syncer_native_nm:
  broadcaster_host_nm:
  broadcaster_native_nm: