version: '3'
services:
  utxo_recovery:
    image: provable/ptokens-utxo-recovery:${VERSION_UTXO_RECOVERY}-${TEE}
    env_file: ../../.env
    environment:
      ROLE: native
    volumes:
      - sync:/home/provable/sync
      - /dev/bus/usb/:/dev/bus/usb
      - pnpm-store:/home/provable/.pnpm-store
      - ../../enclave-proxy:/home/provable/proxy
      - utxo_recovery_nm:/home/provable/syncer/node_modules
    privileged: true
    network_mode: host

volumes:
  utxo_recovery_nm: